# Generated by Django 4.2.16 on 2025-05-01 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{6,10}$', 'Part number must be 6-10 alphanumeric characters')])),
                ('size_mm', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
